#! /bin/bash

docker kill grafana-dashboard
docker rm grafana-dashboard
rm -rf ./logs/*
docker run -d -v $(pwd)/logs:/var/log/supervisor -p 3000:3000 -p 2000:2000 -p 2003:2003 --name grafana-dashboard zenderol/grafana_graphite
